events {}

http {

  server {
    listen 80;
    server_name gitlab.local;

    location / {
      proxy_pass http://devops-company-gitlab-1:80;
    }
  }

  server {
    listen 80;
    server_name jenkins.local;

    location / {
      proxy_pass http://devops-company-jenkins-1:8080;
    }
  }

  server {
    listen 80;
    server_name sonar.local;

    location / {
      proxy_pass http://devops-company-sonarqube-1:9000;
    }
  }

}
